# -*- coding: utf-8 -*-
"""Python Insights Churn de Clientes .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TNPyjkrAUWmUqxqci8hfCXe1PEWy7T8

# Python Insights - Analisando Dados com Python

### Case - Cancelamento de Clientes

Você foi contratado por uma empresa com mais de 800 mil clientes para um projeto de Dados. Recentemente a empresa percebeu que da sua base total de clientes, a maioria são clientes inativos, ou seja, que já cancelaram o serviço.

Precisando melhorar seus resultados ela quer conseguir entender os principais motivos desses cancelamentos e quais as ações mais eficientes para reduzir esse número.

Base de dados e arquivos: https://drive.google.com/drive/folders/1uDesZePdkhiraJmiyeZ-w5tfc8XsNYFZ?usp=drive_link
"""

# Passo a passo
# Passo 1: Importar base de dados
# Passo 2: Visualizar base de dados
# Passo 3: Corrigir cagadas da base de dados
# Passo 4: Análise dos cancelamentos
# Passo 5: Análise da causa dos cancelamentos (como as colunas impactam no cancelamento?)

# !pip install pandas numpy openpyxl nbformat ipykernel plotly
# Passo a passo do projeto
# Passo 1: Importar a base de dados
import pandas as pd
import plotly.express as px

# Criação da variável tabela onde o pandas lê as informações do arquivo e passa para a variável tabela
tabela = pd.read_csv("cancelamentos_sample.csv")

# Passo 2: Visualizar a base de dados
display(tabela)

# Passo 2: Visualizar a base de dados após remoção de colunas dispensáveis
tabela = tabela.drop(columns="CustomerID")

# colunas inúteis - informações que não te ajudam, te atrapalham
display(tabela)

# Passo 3: Corrigir as inconsistências da base de dados
# tabela.info o comando info traz as informações da tabela
display(tabela.info())

# Passo 3: Corrigir as inconsistências da base de dados
# valores vazios - excluir as linhas que têm valores vazios
tabela = tabela.dropna()

display(tabela.info())

# Passo 4: Análise inicial dos cancelamentos

# quantas pessoas cancelaram e quantas não cancelaram
display(tabela["cancelou"].value_counts())

# em percentual
display(tabela["cancelou"].value_counts(normalize=True))
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# Para cada coluna da minha tabela, vou criar um gráfico
for coluna in tabela.columns:
    if coluna != "cancelou" and coluna != "ID_Cliente":
        # barmode="group" serve para colocar as barras de 'cancelou' lado a lado
        fig = px.histogram(tabela, x=coluna, color="cancelou", text_auto=True, barmode="group")
        fig.show()

# Passo 5: Análise das causas dos cancelamentos (como as colunas da base impactam no cancelamento)
# gráficos/dashboards
# !pip install plotly
import plotly.express as px

# Quero entender como cada coluna da base de dados impacta no cancelamento do cliente
# criação do gráfico

# Para cada coluna dentro da minha tabela.columns
# A tabela.columns é a lista com as colunas da minha tabela, ou seja com o nome de cada coluna
# Assim eu percorro a lista através do laço for, e como cada coluna tem o nome de uma coluna, e assim me traz um gráfico para cada coluna
for coluna in tabela.columns:
    # cria o gráfico
    grafico = px.histogram(tabela, x=coluna, color="cancelou", text_auto=True)
    # exibir o grafico
    grafico.show()

"""
# Clientes que ligaram mais de 4x para o call center cancelaram
  # Vamos criar um alerta quando o cliente ligar a 3º vez para o call center

# Todos os clientes do contrato mensal cancelaram
  # Vamos dar desconto nos outros contratos

# Todos os clientes que atrasaram mais de 20 dias, cancelaram
  # Ligar um alerta para o time de cobrança quando o cliente bater 10 dias de atraso

# Se eu resolver esses 3 problemas, como fica a taxa de cancelamento?


"""

# Novo valor da minha tabela vai ser o antigo valor da minha tabela tirando quem ligou mais de 4x para o call center
# Exemplo
# tabela = tabela[condição]

# Call center - olhar a minha base excluindo o problema do call center
tabela = tabela[tabela["ligacoes_callcenter"] <= 4]

display(tabela["cancelou"].value_counts(normalize=True))
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# 1. Simulação: E se os clientes ligassem menos para o Call Center?
# Verificamos no gráfico que acima de 4 ligações o cancelamento é crítico
filtro_callcenter = tabela["ligacoes_callcenter"] <= 4
tabela_sem_callcenter = tabela[filtro_callcenter]

print("\n--- IMPACTO DAS LIGAÇÕES NO CALL CENTER ---")
print(tabela_sem_callcenter["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# Novo valor da minha tabela vai ser o antigo valor da minha tabela tirando quem atrasou mais de 20 dias
# Exemplo
# tabela = tabela[condição]

# dias_atraso - olhar a minha base excluindo o problema de dias_atraso
tabela = tabela[tabela["dias_atraso"] <= 20]

display(tabela["cancelou"].value_counts(normalize=True))
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# 2. Simulação: E se não houvesse atraso superior a 20 dias?
filtro_atraso = tabela["dias_atraso"] <= 20
tabela_sem_atraso = tabela[filtro_atraso]

print("\n--- IMPACTO DO ATRASO NO PAGAMENTO ---")
print(tabela_sem_atraso["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# Novo valor da minha tabela vai ser o antigo valor da minha tabela tirando contratos mensais
# Exemplo
# tabela = tabela[condição]

# duracao_contrato - olhar a minha base excluindo contratos mensais (Monthly)
tabela = tabela[tabela["duracao_contrato"]!="Monthly"]


display(tabela["cancelou"].value_counts(normalize=True))
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# 3. Simulação: E se removêssemos todos os contratos Mensais?
# Na sua tabela, a coluna se chama 'duracao_contrato'
filtro_contrato = tabela["duracao_contrato"] != "Monthly"
tabela_sem_mensal = tabela[filtro_contrato]

print("--- IMPACTO DO CONTRATO MENSAL ---")
print(tabela_sem_mensal["cancelou"].value_counts(normalize=True).map("{:.1%}".format))